### ISSUE TITLE
Bro check out my repo

### ISSUE THREAD

**Issue by muhammad-rabby** [warp-zona/solana-trading-bot-v3#3]
I hope you can use my CLI to make your project even better

**Comment by warp-zona** [comment]
> I hope you can use my CLI to make your project even better

You can contact me on DC, but I won’t easily add any features that haven’t been thoroughly tested. Also, please don’t advertise your repository here, or I will have to ban you.

Thanks,
Zona.

**Comment by warp-zona** [comment]
Alright, it seems I’ll have to enable temporary interaction limits to prevent any spam from now on.
